apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet 
metadata:
  name: skltp-applicationset
  namespace: ntjp-local
spec:
  generators:
  - list:
      elements:
      - cluster: no-op
        url: no-op
        values:
          application: vp
      - cluster: no-op
        url: no-op
        values:
          application: kat
      - cluster: no-op
        url: no-op
        values:
          application: ei
      - cluster: no-op
        url: no-op
        values:
          application: tak
      
  template:
    metadata:
      name: '{{application}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/skltp/{{application}}.git
        targetRevision: feature/skltp-k8s-dev
        path: helm
      destination:
        server: https://kubernetes.default.svc
        namespace: ntjp-local